# Generated by Django 4.2.13 on 2024-07-05 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('iata', models.CharField(default=None, max_length=2)),
                ('icao', models.CharField(default=None, max_length=3)),
                ('callsign', models.CharField(max_length=255)),
                ('active', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'airlines',
            },
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('iata', models.CharField(default=None, max_length=3)),
                ('icao', models.CharField(default=None, max_length=4)),
                ('latitude', models.DecimalField(decimal_places=6, default=None, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=6, default=None, max_digits=12)),
                ('altitude', models.IntegerField(blank=True)),
                ('timezone', models.CharField(default=None, max_length=10, null=True)),
                ('dst', models.CharField(default='U', max_length=1)),
                ('tz_db', models.CharField(max_length=100)),
                ('type', models.CharField(default='airport', max_length=7)),
                ('source', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'airports',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('iso_code', models.CharField(max_length=2)),
                ('dafif_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Equipment_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('iata', models.CharField(max_length=3)),
                ('icao', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'planes',
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeshare', models.CharField(default='Y', max_length=1)),
                ('stops', models.IntegerField(default=0)),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlineapp.airlines')),
                ('equipment', models.ManyToManyField(through='airlineapp.Equipment_list', to='airlineapp.planes')),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_airport', to='airlineapp.airports')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_airport', to='airlineapp.airports')),
            ],
            options={
                'verbose_name_plural': 'routes',
            },
        ),
        migrations.AddField(
            model_name='equipment_list',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airlineapp.planes'),
        ),
        migrations.AddField(
            model_name='equipment_list',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airlineapp.routes'),
        ),
        migrations.AddField(
            model_name='airports',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airlineapp.countries'),
        ),
        migrations.AddField(
            model_name='airlines',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airlineapp.countries'),
        ),
    ]
